image:
  repository: amazon/cloudwatch-agent
  tag: 1.247345.36b249270
  pullPolicy: IfNotPresent

clusterName: ${eks_cluster_name}

resources:
  limits:
    cpu: 200m
    memory: 200Mi
  requests:
    cpu: 200m
    memory: 200Mi

serviceAccount:
  create: true
  annotations: 
    eks.amazonaws.com/role-arn: ${iam_role_arn}
  name: cloudwatch-agent

hostNetwork: false

nodeSelector: {}

tolerations: []

affinity: {} 
