image:
  repository: amazon/cloudwatch-agent
  tag: 1.247345.36b249270
  pullPolicy: IfNotPresent

clusterName: ${eks_cluster_name}

resources:
  limits:
    cpu: 200m
    memory: 200Mi
  requests:
    cpu: 200m
    memory: 200Mi

serviceAccount:
  create: true
  name: cloudwatch-agent

hostNetwork: false

nodeSelector: {}

tolerations: []

affinity: {}